export const QUIZ_DEFAULT_OFFICIAL_SESSION_NUMBERS = [5, 9];
export const QUIZ_SESSION_NUMBERS = QUIZ_DEFAULT_OFFICIAL_SESSION_NUMBERS;
export const QUIZ_ATTEMPT_STATUS_SUBMITTED = 'submitted';
export const QUIZ_ATTEMPT_STATUS_REOPENED = 'reopened';
export const QUIZ_CLASS_STATUS_IDLE = 'idle';
export const QUIZ_CLASS_STATUS_STARTED = 'started';
export const QUIZ_QUESTION_LIMIT = 10;
export const QUIZ_DEFAULT_TIME_LIMIT_MINUTES = 30;
export const QUIZ_MODE_OFFICIAL = 'official_quiz';
export const QUIZ_MODE_PRACTICE = 'practice_quiz';
export const QUIZ_MODES = [QUIZ_MODE_OFFICIAL];
export const QUIZ_QUESTION_TYPE_SINGLE_CHOICE = 'single_choice';
export const QUIZ_QUESTION_TYPE_FILL_BLANK = 'fill_blank';
export const QUIZ_QUESTION_TYPES = [
  QUIZ_QUESTION_TYPE_SINGLE_CHOICE,
  QUIZ_QUESTION_TYPE_FILL_BLANK,
];
export const QUIZ_DIFFICULTY_EASY = 'easy';
export const QUIZ_DIFFICULTY_MEDIUM = 'medium';
export const QUIZ_DIFFICULTY_HARD = 'hard';
export const QUIZ_DIFFICULTIES = [
  QUIZ_DIFFICULTY_EASY,
  QUIZ_DIFFICULTY_MEDIUM,
  QUIZ_DIFFICULTY_HARD,
];
export const QUIZ_DEFAULT_PICK_POLICY = {
  [QUIZ_DIFFICULTY_EASY]: 4,
  [QUIZ_DIFFICULTY_MEDIUM]: 4,
  [QUIZ_DIFFICULTY_HARD]: 2,
};
